name: ci-cd

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      - uses: actions/setup-python@v5
        with:
          python-version: |
              3.9
              3.10
              3.11
      - name: install tox
        run: |
          pip install tox>=4.0
      - name: run tests and docs
        run: tox --parallel

      - name: deploy docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .tox/docs_out/
          force_orphan: true
  cd:
    needs: ci
    runs-on: ubuntu-latest

    environment: test-pypi

    permissions:
      id-token: write
      contents: write

    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    concurrency: release

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Use Python Semantic Release to prepare release
        id: release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: false

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: steps.release.outputs.released == 'true'
