name: ci-cd

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
    contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: install tox
        run: |
         pip install tox
      - name: run tests
        run: tox -e tests
      # - name: build docs
      #   run: |
      #     tox -e docs
      # - name: deploy docs
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      #   with:
      #     publish_branch: gh-pages
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: .tox/docs_out/
      #     force_orphan: true
  cd:
    needs: ci
    runs-on: ubuntu-latest

    environment:
      name: test-pypi

    permissions:
      id-token: write
      contents: write

    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    concurrency: release

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Use Python Semantic Release to prepare release
      id: release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        changelog: false

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: steps.release.outputs.released == 'true'
      with:
        repository-url: https://test.pypi.org/legacy/
